export const mockCategories = [
  // ── TOP LEVEL ──────────────────────────────
  {
    _id: 'c1',
    name: 'Indoor Lighting',
    slug: 'indoor-lighting',
    parentSlug: null,
    image: null,
    bgColor: '#0E1A0B',
    description: 'Premium lighting solutions for every room in your home.',
  },
  {
    _id: 'c2',
    name: 'Outdoor Lighting',
    slug: 'outdoor-lighting',
    parentSlug: null,
    image: null,
    bgColor: '#091320',
    description: 'Illuminate your gardens, gates, and outdoor spaces.',
  },
  {
    _id: 'c3',
    name: 'Chandeliers',
    slug: 'chandeliers',
    parentSlug: null,
    image: null,
    bgColor: '#1A1005',
    description: 'Statement chandeliers for living rooms, dining areas and entrances.',
  },
  {
    _id: 'c4',
    name: 'Decorative Lights',
    slug: 'decorative-lights',
    parentSlug: null,
    image: null,
    bgColor: '#0F0A1A',
    description: 'Rope lights, fairy lights, LED strips and more.',
  },
  {
    _id: 'c5',
    name: 'LED Panels & Bulbs',
    slug: 'led-panels-bulbs',
    parentSlug: null,
    image: null,
    bgColor: '#051520',
    description: 'Energy-efficient LED panels, downlights, and bulbs.',
  },
  {
    _id: 'c6',
    name: 'Smart Lighting',
    slug: 'smart-lighting',
    parentSlug: null,
    image: null,
    bgColor: '#101A0A',
    description: 'App-controlled and voice-activated smart lighting.',
  },

  // ── SUBCATEGORIES OF INDOOR LIGHTING ──────
  {
    _id: 'c7',
    name: 'Ceiling Lights',
    slug: 'ceiling-lights',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#111A0D',
    description: 'Flush mount and semi-flush ceiling lights.',
  },
  {
    _id: 'c8',
    name: 'Pendant Lights',
    slug: 'pendant-lights',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#0D1509',
    description: 'Hanging pendant lights for dining rooms and kitchens.',
  },
  {
    _id: 'c9',
    name: 'Wall Lights',
    slug: 'wall-lights',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#141A0A',
    description: 'Wall sconces and bracket lights.',
  },
  {
    _id: 'c10',
    name: 'Table Lamps',
    slug: 'table-lamps',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#1A1A0A',
    description: 'Bedside and desk table lamps.',
  },
  {
    _id: 'c11',
    name: 'Floor Lamps',
    slug: 'floor-lamps',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#0A1A14',
    description: 'Standing floor lamps for living rooms and bedrooms.',
  },
  {
    _id: 'c12',
    name: 'Spotlights',
    slug: 'spotlights',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#151510',
    description: 'Track spotlights and directional accent lights.',
  },

  // ── SUBCATEGORIES OF OUTDOOR LIGHTING ─────
  {
    _id: 'c13',
    name: 'Garden Lights',
    slug: 'garden-lights',
    parentSlug: 'outdoor-lighting',
    image: null,
    bgColor: '#0A1A10',
    description: 'Spike and post lights for gardens and pathways.',
  },
  {
    _id: 'c14',
    name: 'Gate & Wall Lights',
    slug: 'gate-wall-lights',
    parentSlug: 'outdoor-lighting',
    image: null,
    bgColor: '#0A1015',
    description: 'Security and decorative lights for gates and walls.',
  },
  {
    _id: 'c15',
    name: 'Flood Lights',
    slug: 'flood-lights',
    parentSlug: 'outdoor-lighting',
    image: null,
    bgColor: '#0A0A18',
    description: 'High-power flood lights for security and sports areas.',
  },
  {
    _id: 'c16',
    name: 'Street Lights',
    slug: 'street-lights',
    parentSlug: 'outdoor-lighting',
    image: null,
    bgColor: '#10100A',
    description: 'Commercial and residential street lighting.',
  },

  // ── SUBCATEGORIES OF CHANDELIERS ───────────
  {
    _id: 'c17',
    name: 'Crystal Chandeliers',
    slug: 'crystal-chandeliers',
    parentSlug: 'chandeliers',
    image: null,
    bgColor: '#1A1508',
    description: 'Classic crystal chandeliers for grand interiors.',
  },
  {
    _id: 'c18',
    name: 'Modern Chandeliers',
    slug: 'modern-chandeliers',
    parentSlug: 'chandeliers',
    image: null,
    bgColor: '#0A1518',
    description: 'Contemporary chandelier designs for modern homes.',
  },
];

export const mockProducts = [
  {
    _id: 'p1',
    name: 'Nordic Pendant Light',
    slug: 'nordic-pendant-light',
    categorySlug: 'pendant-lights',
    category: { name: 'Pendant Lights', slug: 'pendant-lights' },
    price: 8500,
    salePrice: null,
    isNewArrival: true,
    isFeatured: true,
    images: [],
    avgRating: 4.8,
    reviewCount: 24,
    stockStatus: 'inStock',
    sku: 'GLH-001',
  },
  {
    _id: 'p2',
    name: 'Minimalist Wall Sconce',
    slug: 'minimalist-wall-sconce',
    categorySlug: 'wall-lights',
    category: { name: 'Wall Lights', slug: 'wall-lights' },
    price: 6800,
    salePrice: 5200,
    isNewArrival: false,
    isFeatured: true,
    images: [],
    avgRating: 4.6,
    reviewCount: 18,
    stockStatus: 'inStock',
    sku: 'GLH-002',
  },
  {
    _id: 'p3',
    name: 'Crystal Chandelier — 12 Arms',
    slug: 'crystal-chandelier-12-arms',
    categorySlug: 'crystal-chandeliers',
    category: { name: 'Crystal Chandeliers', slug: 'crystal-chandeliers' },
    price: 24000,
    salePrice: null,
    isNewArrival: true,
    isFeatured: false,
    images: [],
    avgRating: 5.0,
    reviewCount: 11,
    stockStatus: 'limitedStock',
    sku: 'GLH-003',
  },
  {
    _id: 'p4',
    name: 'Garden Spike Light',
    slug: 'garden-spike-light',
    categorySlug: 'garden-lights',
    category: { name: 'Garden Lights', slug: 'garden-lights' },
    price: 3200,
    salePrice: null,
    isNewArrival: true,
    isFeatured: false,
    images: [],
    avgRating: 4.5,
    reviewCount: 9,
    stockStatus: 'inStock',
    sku: 'GLH-004',
  },
  {
    _id: 'p5',
    name: 'LED Panel 60×60cm',
    slug: 'led-panel-60x60',
    categorySlug: 'led-panels-bulbs',
    category: { name: 'LED Panels & Bulbs', slug: 'led-panels-bulbs' },
    price: 4500,
    salePrice: 3800,
    isNewArrival: false,
    isFeatured: true,
    images: [],
    avgRating: 4.7,
    reviewCount: 32,
    stockStatus: 'inStock',
    sku: 'GLH-005',
  },
  {
    _id: 'p6',
    name: 'Classic Bedside Table Lamp',
    slug: 'classic-bedside-table-lamp',
    categorySlug: 'table-lamps',
    category: { name: 'Table Lamps', slug: 'table-lamps' },
    price: 5800,
    salePrice: null,
    isNewArrival: false,
    isFeatured: true,
    images: [],
    avgRating: 4.9,
    reviewCount: 15,
    stockStatus: 'inStock',
    sku: 'GLH-006',
  },
  {
    _id: 'p7',
    name: 'Industrial Floor Lamp',
    slug: 'industrial-floor-lamp',
    categorySlug: 'floor-lamps',
    category: { name: 'Floor Lamps', slug: 'floor-lamps' },
    price: 12000,
    salePrice: 9500,
    isNewArrival: true,
    isFeatured: false,
    images: [],
    avgRating: 4.4,
    reviewCount: 7,
    stockStatus: 'inStock',
    sku: 'GLH-007',
  },
  {
    _id: 'p8',
    name: 'LED Rope Light — 5 Meters',
    slug: 'led-rope-light-5m',
    categorySlug: 'decorative-lights',
    category: { name: 'Decorative Lights', slug: 'decorative-lights' },
    price: 1800,
    salePrice: null,
    isNewArrival: true,
    isFeatured: false,
    images: [],
    avgRating: 4.3,
    reviewCount: 41,
    stockStatus: 'inStock',
    sku: 'GLH-008',
  },
  {
    _id: 'p9',
    name: 'Modern Flush Ceiling Light',
    slug: 'modern-flush-ceiling-light',
    categorySlug: 'ceiling-lights',
    category: { name: 'Ceiling Lights', slug: 'ceiling-lights' },
    price: 7200,
    salePrice: null,
    isNewArrival: false,
    isFeatured: true,
    images: [],
    avgRating: 4.6,
    reviewCount: 22,
    stockStatus: 'inStock',
    sku: 'GLH-009',
  },
  {
    _id: 'p10',
    name: 'Outdoor Security Flood Light',
    slug: 'outdoor-security-flood-light',
    categorySlug: 'flood-lights',
    category: { name: 'Flood Lights', slug: 'flood-lights' },
    price: 5500,
    salePrice: 4200,
    isNewArrival: false,
    isFeatured: false,
    images: [],
    avgRating: 4.5,
    reviewCount: 19,
    stockStatus: 'inStock',
    sku: 'GLH-010',
  },
  {
    _id: 'p11',
    name: 'Gold Crystal Chandelier — 8 Arms',
    slug: 'gold-crystal-chandelier-8-arms',
    categorySlug: 'crystal-chandeliers',
    category: { name: 'Crystal Chandeliers', slug: 'crystal-chandeliers' },
    price: 18500,
    salePrice: null,
    isNewArrival: true,
    isFeatured: true,
    images: [],
    avgRating: 4.9,
    reviewCount: 8,
    stockStatus: 'inStock',
    sku: 'GLH-011',
  },
  {
    _id: 'p12',
    name: 'Gate Wall Bracket Light',
    slug: 'gate-wall-bracket-light',
    categorySlug: 'gate-wall-lights',
    category: { name: 'Gate & Wall Lights', slug: 'gate-wall-lights' },
    price: 2800,
    salePrice: null,
    isNewArrival: false,
    isFeatured: false,
    images: [],
    avgRating: 4.4,
    reviewCount: 14,
    stockStatus: 'inStock',
    sku: 'GLH-012',
  },
];

export const mockReviews = [
  {
    _id: 'r1',
    name: 'Ahmed K.',
    city: 'Lahore',
    rating: 5,
    title: 'Absolutely stunning quality',
    body: 'The pendant light transformed our dining room completely. Quality is exceptional and delivery was faster than expected. Will definitely order again.',
  },
  {
    _id: 'r2',
    name: 'Sara M.',
    city: 'Karachi',
    rating: 5,
    title: 'Perfect for our new apartment',
    body: 'Hassaan helped us choose the right fixtures for every room. Very professional service and products are worth every rupee.',
  },
  {
    _id: 'r3',
    name: 'Bilal R.',
    city: 'Islamabad',
    rating: 5,
    title: 'Best lighting store in Pakistan',
    body: 'Ordered chandeliers for our entire house. International standard quality. Packaging was excellent, nothing damaged in transit.',
  },
];
