export const mockCategories = [
  // ── TOP LEVEL ──────────────────────────────
  {
    _id: 'c1',
    name: 'Indoor Lighting',
    slug: 'indoor-lighting',
    parentSlug: null,
    image: null,
    bgColor: '#0E1A0B',
    description: 'Premium lighting solutions for every room in your home.',
  },
  {
    _id: 'c2',
    name: 'Outdoor Lighting',
    slug: 'outdoor-lighting',
    parentSlug: null,
    image: null,
    bgColor: '#091320',
    description: 'Illuminate your gardens, gates, and outdoor spaces.',
  },
  {
    _id: 'c3',
    name: 'Chandeliers',
    slug: 'chandeliers',
    parentSlug: null,
    image: null,
    bgColor: '#1A1005',
    description: 'Statement chandeliers for living rooms, dining areas and entrances.',
  },
  {
    _id: 'c4',
    name: 'Decorative Lights',
    slug: 'decorative-lights',
    parentSlug: null,
    image: null,
    bgColor: '#0F0A1A',
    description: 'Rope lights, fairy lights, LED strips and more.',
  },
  {
    _id: 'c5',
    name: 'LED Panels & Bulbs',
    slug: 'led-panels-bulbs',
    parentSlug: null,
    image: null,
    bgColor: '#051520',
    description: 'Energy-efficient LED panels, downlights, and bulbs.',
  },
  {
    _id: 'c6',
    name: 'Smart Lighting',
    slug: 'smart-lighting',
    parentSlug: null,
    image: null,
    bgColor: '#101A0A',
    description: 'App-controlled and voice-activated smart lighting.',
  },

  // ── SUBCATEGORIES OF INDOOR LIGHTING ──────
  {
    _id: 'c7',
    name: 'Ceiling Lights',
    slug: 'ceiling-lights',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#111A0D',
    description: 'Flush mount and semi-flush ceiling lights.',
  },
  {
    _id: 'c8',
    name: 'Pendant Lights',
    slug: 'pendant-lights',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#0D1509',
    description: 'Hanging pendant lights for dining rooms and kitchens.',
  },
  {
    _id: 'c9',
    name: 'Wall Lights',
    slug: 'wall-lights',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#141A0A',
    description: 'Wall sconces and bracket lights.',
  },
  {
    _id: 'c10',
    name: 'Table Lamps',
    slug: 'table-lamps',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#1A1A0A',
    description: 'Bedside and desk table lamps.',
  },
  {
    _id: 'c11',
    name: 'Floor Lamps',
    slug: 'floor-lamps',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#0A1A14',
    description: 'Standing floor lamps for living rooms and bedrooms.',
  },
  {
    _id: 'c12',
    name: 'Spotlights',
    slug: 'spotlights',
    parentSlug: 'indoor-lighting',
    image: null,
    bgColor: '#151510',
    description: 'Track spotlights and directional accent lights.',
  },

  // ── SUBCATEGORIES OF OUTDOOR LIGHTING ─────
  {
    _id: 'c13',
    name: 'Garden Lights',
    slug: 'garden-lights',
    parentSlug: 'outdoor-lighting',
    image: null,
    bgColor: '#0A1A10',
    description: 'Spike and post lights for gardens and pathways.',
  },
  {
    _id: 'c14',
    name: 'Gate & Wall Lights',
    slug: 'gate-wall-lights',
    parentSlug: 'outdoor-lighting',
    image: null,
    bgColor: '#0A1015',
    description: 'Security and decorative lights for gates and walls.',
  },
  {
    _id: 'c15',
    name: 'Flood Lights',
    slug: 'flood-lights',
    parentSlug: 'outdoor-lighting',
    image: null,
    bgColor: '#0A0A18',
    description: 'High-power flood lights for security and sports areas.',
  },
  {
    _id: 'c16',
    name: 'Street Lights',
    slug: 'street-lights',
    parentSlug: 'outdoor-lighting',
    image: null,
    bgColor: '#10100A',
    description: 'Commercial and residential street lighting.',
  },

  // ── SUBCATEGORIES OF CHANDELIERS ───────────
  {
    _id: 'c17',
    name: 'Crystal Chandeliers',
    slug: 'crystal-chandeliers',
    parentSlug: 'chandeliers',
    image: null,
    bgColor: '#1A1508',
    description: 'Classic crystal chandeliers for grand interiors.',
  },
  {
    _id: 'c18',
    name: 'Modern Chandeliers',
    slug: 'modern-chandeliers',
    parentSlug: 'chandeliers',
    image: null,
    bgColor: '#0A1518',
    description: 'Contemporary chandelier designs for modern homes.',
  },
];

export const mockProducts = [
  {
    _id: 'p1',
    name: 'Nordic Pendant Light',
    slug: 'nordic-pendant-light',
    categorySlug: 'pendant-lights',
    category: { name: 'Pendant Lights', slug: 'pendant-lights' },
    price: 8500,
    salePrice: null,
    isNewArrival: true,
    isFeatured: true,
    images: [],
    avgRating: 4.8,
    reviewCount: 24,
    stockStatus: 'inStock',
    sku: 'GLH-001',
    shortDesc: 'Minimalist Nordic-style pendant in brushed brass and frosted glass.',
    description: 'The Nordic Pendant brings Scandinavian elegance to Pakistani interiors. Its frosted glass diffuser creates a warm, even glow perfect for dining tables and kitchen islands. The adjustable hanging cord allows installation at any height between 30cm and 150cm, making it ideal for rooms with varying ceiling heights.',
    specs: {
      wattage: '40W (E27)',
      lumens: '3200lm',
      colorTemp: 'Warm White (3000K)',
      fitting: 'E27 (standard)',
      ipRating: 'IP20 (indoor only)',
      dimensions: 'Ø28cm × H120cm (adjustable)',
      material: 'Brushed brass, frosted glass',
      dimmable: true,
      warranty: '2 Years',
    },
  },
  {
    _id: 'p2',
    name: 'Minimalist Wall Sconce',
    slug: 'minimalist-wall-sconce',
    categorySlug: 'wall-lights',
    category: { name: 'Wall Lights', slug: 'wall-lights' },
    price: 6800,
    salePrice: 5200,
    isNewArrival: false,
    isFeatured: true,
    images: [],
    avgRating: 4.6,
    reviewCount: 18,
    stockStatus: 'inStock',
    sku: 'GLH-002',
    shortDesc: 'Sleek matte black wall sconce for corridor and bedroom accent lighting.',
    description: 'The Minimalist Wall Sconce delivers clean architectural lines that complement both modern and contemporary interiors. Its adjustable arm allows the light to be directed precisely where needed. Available in matte black, this fixture works beautifully as a bedside reading light or corridor accent.',
    specs: {
      wattage: '20W (E27)',
      lumens: '1600lm',
      colorTemp: 'Warm White (3000K)',
      fitting: 'E27 (standard)',
      ipRating: 'IP20 (indoor only)',
      dimensions: '25cm × H12cm',
      material: 'Matte black powder-coated metal',
      dimmable: true,
      warranty: '1 Year',
    },
  },
  {
    _id: 'p3',
    name: 'Crystal Chandelier — 12 Arms',
    slug: 'crystal-chandelier-12-arms',
    categorySlug: 'crystal-chandeliers',
    category: { name: 'Crystal Chandeliers', slug: 'crystal-chandeliers' },
    price: 24000,
    salePrice: null,
    isNewArrival: true,
    isFeatured: false,
    images: [],
    avgRating: 5.0,
    reviewCount: 11,
    stockStatus: 'limitedStock',
    sku: 'GLH-003',
    shortDesc: 'Grand 12-arm crystal chandelier with K9 crystal drops and chrome frame.',
    description: 'A statement piece for grand entrances, formal dining rooms, and living halls. The 12-arm configuration holds K9 lead crystal drops that refract light beautifully across your ceiling. The chrome frame is precision-machined for a flawless finish. Compatible with dimmer switches for mood lighting.',
    specs: {
      wattage: '12 × 40W (E14)',
      lumens: '14400lm (combined)',
      colorTemp: 'Warm White (2700K)',
      fitting: 'E14 (candle)',
      ipRating: 'IP20 (indoor only)',
      dimensions: 'Ø80cm × H100cm',
      material: 'K9 crystal, chrome frame',
      dimmable: true,
      warranty: '2 Years',
    },
  },
  {
    _id: 'p4',
    name: 'Garden Spike Light',
    slug: 'garden-spike-light',
    categorySlug: 'garden-lights',
    category: { name: 'Garden Lights', slug: 'garden-lights' },
    price: 3200,
    salePrice: null,
    isNewArrival: true,
    isFeatured: false,
    images: [],
    avgRating: 4.5,
    reviewCount: 9,
    stockStatus: 'inStock',
    sku: 'GLH-004',
    shortDesc: 'Weatherproof spike light for garden paths and plant bed accents.',
    description: 'Designed for Pakistani outdoor conditions, the Garden Spike Light is fully weatherproof and built to last through monsoon seasons. The ground spike allows easy installation without tools. Ideal for illuminating pathways, trees, and garden borders. Sold in packs or individually.',
    specs: {
      wattage: '10W (integrated LED)',
      lumens: '800lm',
      colorTemp: 'Cool White (4000K)',
      fitting: 'Integrated LED (non-replaceable)',
      ipRating: 'IP65 (weatherproof)',
      dimensions: 'H30cm (including spike)',
      material: 'Die-cast aluminium, tempered glass',
      dimmable: false,
      warranty: '1 Year',
    },
  },
  {
    _id: 'p5',
    name: 'LED Panel 60×60cm',
    slug: 'led-panel-60x60',
    categorySlug: 'led-panels-bulbs',
    category: { name: 'LED Panels & Bulbs', slug: 'led-panels-bulbs' },
    price: 4500,
    salePrice: 3800,
    isNewArrival: false,
    isFeatured: true,
    images: [],
    avgRating: 4.7,
    reviewCount: 32,
    stockStatus: 'inStock',
    sku: 'GLH-005',
    shortDesc: 'Energy-efficient 40W LED panel for offices, kitchens, and commercial ceilings.',
    description: 'The GLH LED Panel is engineered for commercial and residential false ceilings. It delivers uniform, flicker-free illumination across the full panel surface — eliminating the harsh spots common in cheaper alternatives. Compatible with standard 60×60 grid ceilings. Driver built-in; no external driver required.',
    specs: {
      wattage: '40W (built-in driver)',
      lumens: '3600lm',
      colorTemp: 'Natural White (4000K)',
      fitting: 'Surface mount or recessed (clips included)',
      ipRating: 'IP40',
      dimensions: '600mm × 600mm × 10mm',
      material: 'Aluminium frame, diffuser panel',
      dimmable: false,
      warranty: '3 Years',
    },
  },
  {
    _id: 'p6',
    name: 'Classic Bedside Table Lamp',
    slug: 'classic-bedside-table-lamp',
    categorySlug: 'table-lamps',
    category: { name: 'Table Lamps', slug: 'table-lamps' },
    price: 5800,
    salePrice: null,
    isNewArrival: false,
    isFeatured: true,
    images: [],
    avgRating: 4.9,
    reviewCount: 15,
    stockStatus: 'inStock',
    sku: 'GLH-006',
    shortDesc: 'Elegant ceramic table lamp with linen shade, ideal for bedside or study use.',
    description: 'The Classic Bedside Table Lamp combines a hand-glazed ceramic base with a natural linen shade to create warm, diffused light perfect for reading and relaxing. The on/off rotary switch is built into the cord for convenience. Works with standard E27 bulbs — a 12W LED bulb is included.',
    specs: {
      wattage: '60W max (E27), 12W LED included',
      lumens: '2700lm (with included bulb)',
      colorTemp: 'Warm White (3000K)',
      fitting: 'E27 (standard)',
      ipRating: 'IP20 (indoor only)',
      dimensions: 'Ø20cm × H45cm',
      material: 'Ceramic base, linen shade',
      dimmable: false,
      warranty: '1 Year',
    },
  },
  {
    _id: 'p7',
    name: 'Industrial Floor Lamp',
    slug: 'industrial-floor-lamp',
    categorySlug: 'floor-lamps',
    category: { name: 'Floor Lamps', slug: 'floor-lamps' },
    price: 12000,
    salePrice: 9500,
    isNewArrival: true,
    isFeatured: false,
    images: [],
    avgRating: 4.4,
    reviewCount: 7,
    stockStatus: 'inStock',
    sku: 'GLH-007',
    shortDesc: 'Adjustable industrial-style floor lamp in black metal, ideal for living rooms.',
    description: 'A bold industrial aesthetic meets functional task lighting. The adjustable arm and head allow you to direct light exactly where you need it — ideal for reading corners, home offices, and living rooms. The weighted base ensures stability. Compatible with any E27 bulb up to 100W.',
    specs: {
      wattage: '60W max (E27)',
      lumens: '3200lm (with recommended 40W LED)',
      colorTemp: 'Warm White (3000K) recommended',
      fitting: 'E27 (standard)',
      ipRating: 'IP20 (indoor only)',
      dimensions: 'H150cm (fully extended), base Ø25cm',
      material: 'Powder-coated black steel',
      dimmable: false,
      warranty: '1 Year',
    },
  },
  {
    _id: 'p8',
    name: 'LED Rope Light — 5 Meters',
    slug: 'led-rope-light-5m',
    categorySlug: 'decorative-lights',
    category: { name: 'Decorative Lights', slug: 'decorative-lights' },
    price: 1800,
    salePrice: null,
    isNewArrival: true,
    isFeatured: false,
    images: [],
    avgRating: 4.3,
    reviewCount: 41,
    stockStatus: 'inStock',
    sku: 'GLH-008',
    shortDesc: 'Flexible 5-meter LED rope light for indoor decoration and festive lighting.',
    description: 'The GLH LED Rope Light is a customer favourite for Eid decorations, bedroom cove lighting, and shop display accents. The flexible PVC tube is easy to bend around curves and can be cut at marked intervals. Includes a 2-pin plug and a basic controller for steady-on and flash modes.',
    specs: {
      wattage: '20W (4W per metre)',
      lumens: '1500lm total',
      colorTemp: 'Warm White (3000K)',
      fitting: 'Plug-in (2-pin Pakistan standard)',
      ipRating: 'IP20 (indoor use only)',
      dimensions: '5000mm × Ø12mm',
      material: 'PVC outer, copper core',
      dimmable: false,
      warranty: '1 Year',
    },
  },
  {
    _id: 'p9',
    name: 'Modern Flush Ceiling Light',
    slug: 'modern-flush-ceiling-light',
    categorySlug: 'ceiling-lights',
    category: { name: 'Ceiling Lights', slug: 'ceiling-lights' },
    price: 7200,
    salePrice: null,
    isNewArrival: false,
    isFeatured: true,
    images: [],
    avgRating: 4.6,
    reviewCount: 22,
    stockStatus: 'inStock',
    sku: 'GLH-009',
    shortDesc: 'Circular LED flush-mount ceiling light in brushed nickel for bedrooms and living rooms.',
    description: 'The Modern Flush Ceiling Light offers a clean, low-profile look ideal for rooms with standard ceiling heights. The integrated LED chip eliminates the need for bulb replacements for up to 50,000 hours of use. The brushed nickel finish pairs well with white, grey, and earth-tone interiors.',
    specs: {
      wattage: '36W (integrated LED)',
      lumens: '3000lm',
      colorTemp: 'Warm White (3000K)',
      fitting: 'Integrated LED (no bulb replacement)',
      ipRating: 'IP20 (indoor only)',
      dimensions: 'Ø50cm × H10cm',
      material: 'Brushed nickel frame, frosted acrylic diffuser',
      dimmable: true,
      warranty: '2 Years',
    },
  },
  {
    _id: 'p10',
    name: 'Outdoor Security Flood Light',
    slug: 'outdoor-security-flood-light',
    categorySlug: 'flood-lights',
    category: { name: 'Flood Lights', slug: 'flood-lights' },
    price: 5500,
    salePrice: 4200,
    isNewArrival: false,
    isFeatured: false,
    images: [],
    avgRating: 4.5,
    reviewCount: 19,
    stockStatus: 'inStock',
    sku: 'GLH-010',
    shortDesc: 'High-power 50W LED flood light for building facades, driveways, and security lighting.',
    description: 'Built to handle Pakistan\'s harsh outdoor conditions, the Security Flood Light is fully waterproof and dust-proof. The die-cast aluminium housing dissipates heat efficiently, extending LED life. An adjustable bracket allows mounting on walls, poles, and ceilings at any angle from 0° to 180°.',
    specs: {
      wattage: '50W (integrated LED)',
      lumens: '5000lm',
      colorTemp: 'Cool White (6500K)',
      fitting: 'Integrated LED (non-replaceable)',
      ipRating: 'IP65 (dust and waterproof)',
      dimensions: '250mm × 180mm × 40mm',
      material: 'Die-cast aluminium housing, tempered glass',
      dimmable: false,
      warranty: '2 Years',
    },
  },
  {
    _id: 'p11',
    name: 'Gold Crystal Chandelier — 8 Arms',
    slug: 'gold-crystal-chandelier-8-arms',
    categorySlug: 'crystal-chandeliers',
    category: { name: 'Crystal Chandeliers', slug: 'crystal-chandeliers' },
    price: 18500,
    salePrice: null,
    isNewArrival: true,
    isFeatured: true,
    images: [],
    avgRating: 4.9,
    reviewCount: 8,
    stockStatus: 'inStock',
    sku: 'GLH-011',
    shortDesc: 'Luxurious 8-arm chandelier with gold-tone frame and K9 crystal pendants.',
    description: 'The Gold Crystal Chandelier is crafted for Pakistani drawing rooms and formal dining spaces where luxury is a priority. Eight curved arms are finished in 24-carat gold plating, each adorned with hand-cut K9 crystal pendants. The warm 2700K glow creates an intimate, candlelit atmosphere.',
    specs: {
      wattage: '8 × 40W (E14)',
      lumens: '9600lm (combined)',
      colorTemp: 'Warm White (2700K)',
      fitting: 'E14 (candle)',
      ipRating: 'IP20 (indoor only)',
      dimensions: 'Ø65cm × H90cm',
      material: '24K gold-plated frame, K9 crystal',
      dimmable: true,
      warranty: '2 Years',
    },
  },
  {
    _id: 'p12',
    name: 'Gate Wall Bracket Light',
    slug: 'gate-wall-bracket-light',
    categorySlug: 'gate-wall-lights',
    category: { name: 'Gate & Wall Lights', slug: 'gate-wall-lights' },
    price: 2800,
    salePrice: null,
    isNewArrival: false,
    isFeatured: false,
    images: [],
    avgRating: 4.4,
    reviewCount: 14,
    stockStatus: 'inStock',
    sku: 'GLH-012',
    shortDesc: 'Classic lantern-style wall bracket light for gate posts and exterior walls.',
    description: 'The Gate Wall Bracket Light gives a traditional lantern look to your home\'s exterior. Its IP44 rating means it\'s suitable for covered outdoor locations like gate pillars, porches, and covered walkways. The black finish resists weathering and does not chip or fade in direct sunlight.',
    specs: {
      wattage: '15W (E27)',
      lumens: '1000lm',
      colorTemp: 'Warm White (3000K)',
      fitting: 'E27 (standard)',
      ipRating: 'IP44 (splash resistant)',
      dimensions: '25cm × 20cm × 30cm',
      material: 'Cast iron body, clear glass panels',
      dimmable: false,
      warranty: '1 Year',
    },
  },
];

export const mockReviews = [
  {
    _id: 'r1',
    name: 'Ahmed K.',
    city: 'Lahore',
    rating: 5,
    title: 'Absolutely stunning quality',
    body: 'The pendant light transformed our dining room completely. Quality is exceptional and delivery was faster than expected. Will definitely order again.',
  },
  {
    _id: 'r2',
    name: 'Sara M.',
    city: 'Karachi',
    rating: 5,
    title: 'Perfect for our new apartment',
    body: 'Hassaan helped us choose the right fixtures for every room. Very professional service and products are worth every rupee.',
  },
  {
    _id: 'r3',
    name: 'Bilal R.',
    city: 'Islamabad',
    rating: 5,
    title: 'Best lighting store in Pakistan',
    body: 'Ordered chandeliers for our entire house. International standard quality. Packaging was excellent, nothing damaged in transit.',
  },
];
